### ISSUE TITLE
Documentation suggestions. 

### ISSUE THREAD

**Issue by semaphoreP** [JuliaHCI/ADI.jl#39]
Going through your documentation, I think it would be helpful to be more explicit in the requirements for the input data format. In particular:

- Mentioning image registration requirements. Is the star at the center of the image (what about for even-sized arrays) for all images? 
- The format of the angles vector. Also, whether this is CCW or CW rotation, and whether it is in degrees or radians. 

For the SDI feature, I understand it is still under development but here are some suggestions:
- Typically, this is done in IFS images where multiple wavelengths are acquired at the same time. I'd suggest leading with the nf dimension rather than the nlam dimension
- How is the `scales` argument defined? I think there is a 1/x degeneracy without knowing its definition (or an example computing this term from the wavelength).

**Comment by mileslucas** [comment]
Thanks for the comments- I remember when I was first learning these things I had to grok source code, so I love the suggestion to clarify the data structures in the docs.

For the SDI, so far I've been using the same model that VIP uses, which permutes the dims with the spectral axis first. I've made sure to include a note in the docs discussing the potential discrepancy and made a note about how to form the scales from the wavelengths.

Again, thanks for the in-depth comments- everything starts to look better the more eyes look at it!

**Comment by semaphoreP** [comment]
Yeah, exactly. A lot of these conventions vary between instruments/teams/codebases, so it's always good to specify! 

I was going through the examples in the docs, and mostly had no trouble (nice tutorial!). The one issue I ran into was in the beta Pic example. There was no explicit instructions to install HCIToolbox before starting the tutorial, so the `mask_circle` function didn't exist. After I installed HCIToolbox and started a new Julia instance, I didn't find the behavior that `mask_circle` was imported automatically with ADI. I had to manually import it with `using HCIToolbox: mask_circle`. 

I was also wondering how you measure the photometry of the fake planets. Is this through aperture photometry? It could be worth stating somewhere in the docstrings, since there are multiple ways to do fake planet photometry (I use matched filtering for the most part).

**Comment by mileslucas** [comment]
> There was no explicit instructions to install HCIToolbox before starting the tutorial, so the mask_circle function didn't exist

I think this is due to versioning- I switched to automatically re-export `HCIToolbox.jl` within `ADI.jl` but that's only on master (ADI version `0.5.3`).

you'll need to update the code to master to match the documentation that is live right now (at least the `dev` docs- the `stable` docs [still show the import](https://juliahci.github.io/ADI.jl/stable/examples/betapictoris/#Setup))

>  how you measure the photometry of the fake planets

I'm doing the same thing VIP does which is circular aperture photometry, using [Photometry.jl](https://github.com/juliaastro/photometry.jl). I'll make sure to add a note to the contrast and throughput doc strings about this- thanks!

**Comment by semaphoreP** [comment]
Ah yes, I'm on the stable build. Thanks for checking. Feel free to close this issue, after you update the docstring regarding aperture photometry.
