### ISSUE TITLE
Paper comments

### ISSUE THREAD

**Issue by semaphoreP** [JuliaHCI/ADI.jl#40]
Overall, the paper looks great. The one thing I found confusing is the distinction between "posterior analysis" and "forward modeling". I agree there is a distinction here, but I feel like "posterior analysis" is quite vague, and forward modeling may also fall into that category since the forward models are compared to the residual images in similar ways. It seems like everything under the category of "posterior analysis" currently could be more precisely categorized as "detection metrics". 

The table comparing existing packages is very useful for the community and overall I found this summary excellent. As the maintainer of pyklip, I would note that pyklip also supports nmf and weighted PCA algorithms, although they are not available in the forward modeling framework.

**Comment by mileslucas** [comment]
Thanks for the comments- I've revised the language of the section to use "detection metrics" and clear up some of the distinctions between that and "forward models". Unfortunately, I don't think the table is going to fit in the paper, so I've copied it into the docs. I've revised the pyKLIP algs, too (thanks for pointing that out!).

**Comment by semaphoreP** [comment]
Thanks!
